[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.21"

[features]
resolution = true
skip-lint = false

[programs.localnet]
drawsol = "FwM598mwYfusUtpuN66f8bteTTubL9SJJ5RuPiVonuUb"

[programs.devnet]
drawsol = "FwM598mwYfusUtpuN66f8bteTTubL9SJJ5RuPiVonuUb"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path tests-svm/Cargo.toml -- --test-threads=4"
